<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>$(Authors.Replace("Î", "I").Replace("é", "e").Replace("'", "").Replace(" ", "")).$(AssemblyName)</PackageId>
    <Authors>Îakaré Software'oka</Authors>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/Iakare-Software-oka/CoreLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Iakare-Software-oka/CoreLibrary</RepositoryUrl>
    <NeutralLanguage>pt-BR</NeutralLanguage>
  </PropertyGroup>

</Project>
