//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acessor is null..
        /// </summary>
        internal static string ACESSOR_NULL {
            get {
                return ResourceManager.GetString("ACESSOR_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAPIBARA_CORS.
        /// </summary>
        internal static string CORS_POLICY_NAME {
            get {
                return ResourceManager.GetString("CORS_POLICY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        internal static string FORMAT {
            get {
                return ResourceManager.GetString("FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HttpContex can not be null..
        /// </summary>
        internal static string HTTP_CONTEXT_NULL {
            get {
                return ResourceManager.GetString("HTTP_CONTEXT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity can not be null..
        /// </summary>
        internal static string IDENTITY_NULL {
            get {
                return ResourceManager.GetString("IDENTITY_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oauth2.
        /// </summary>
        internal static string OAUTH_SCHEME {
            get {
                return ResourceManager.GetString("OAUTH_SCHEME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT Authorization header using the Bearer scheme.
        ///                                                            Enter &apos;Bearer&apos;[space] and then your token in the text input below.
        ///                                                            Example: Bearer 12345abcdef.
        /// </summary>
        internal static string SECURITY_SCHEME_DESCRIPTION {
            get {
                return ResourceManager.GetString("SECURITY_SCHEME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string SECURITY_SCHEME_HEADER_NAME {
            get {
                return ResourceManager.GetString("SECURITY_SCHEME_HEADER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não autorizado..
        /// </summary>
        internal static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User can not be null..
        /// </summary>
        internal static string USER_NULL {
            get {
                return ResourceManager.GetString("USER_NULL", resourceCulture);
            }
        }
    }
}
