<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Îakaré Software'Oka</Authors>
    <NeutralLanguage>pt-BR</NeutralLanguage>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <PackageId>ISO.$(AssemblyName)</PackageId>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/luca16s/IakareLibraries</PackageProjectUrl>
    <RepositoryUrl>https://github.com/luca16s/IakareLibraries</RepositoryUrl>
    <RepositoryType></RepositoryType>
    <Title>Îakaré Software'Oka - Core Library</Title>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Utils\**" />
    <EmbeddedResource Remove="Utils\**" />
    <None Remove="Utils\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.1.0" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.5.108">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
