<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Îakaré Softwareoka Inc. - Event Library</Title>
    <Authors>Îakaré Softwareoka Inc.</Authors>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/Iakare-Softwareoka-Inc/Library</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Iakare-Softwareoka-Inc/Library</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="MassTransit" Version="8.3.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.Interfaces\Core.Interfaces.csproj" />
    <ProjectReference Include="..\Core.Models\Core.Models.csproj" />
  </ItemGroup>

</Project>
