<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Îakaré Software'Oka - CrossCutting Library</Title>
    <PackageId>ISO.$(AssemblyName)</PackageId>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <Authors>Îakaré Software'Oka</Authors>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/luca16s/IakareLibraries</PackageProjectUrl>
    <RepositoryUrl>https://github.com/luca16s/IakareLibraries</RepositoryUrl>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.5.0" />
  </ItemGroup>

</Project>
