<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>Îakaré Software'Oka - CrossCutting Library</Title>
    <PackageId>ISO.$(AssemblyName)</PackageId>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Îakaré Software'Oka</Authors>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/luca16s/IakareLibraries</PackageProjectUrl>
    <RepositoryUrl>https://github.com/luca16s/IakareLibraries</RepositoryUrl>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.DataAnnotations" Version="2.2.0" />
  </ItemGroup>

</Project>
