<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Îakaré Software'oka</Authors>
    <NeutralLanguage>pt-BR</NeutralLanguage>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <PackageId>$(Authors.Replace("Î", "I").Replace("é", "e").Replace("'", "").Replace(" ", "")).$(AssemblyName)</PackageId>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/Iakare-Software-oka/CoreLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Iakare-Software-oka/CoreLibrary</RepositoryUrl>
    <RepositoryType></RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Utils\" />
  </ItemGroup>

</Project>
