<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>ISO.$(AssemblyName)</PackageId>
    <Authors>Îakaré Softwareoka Inc.</Authors>
    <Copyright>$(Authors)</Copyright>
    <PackageProjectUrl>https://github.com/Iakare-Softwareoka-Inc/Library</PackageProjectUrl>
    <RepositoryUrl>https://github.com/luca16s/IakareLibraries</RepositoryUrl>
    <NeutralLanguage>pt-BR</NeutralLanguage>
    <Title>Îakaré Softwareoka Inc. - Data Library</Title>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
    <FileVersion>$(VersionPrefix)</FileVersion>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

</Project>
