<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageProjectUrl>https://github.com/Iakare-Softwareoka-Inc/Library</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Iakare-Softwareoka-Inc/Library</RepositoryUrl>
    <Copyright>$(Authors)</Copyright>
    <Authors>Îakaré Softwareoka Inc.</Authors>
    <Title>Îakaré Softwareoka Inc. - Cross Cutting Library</Title>
    <PackageId>ISO.$(AssemblyName)</PackageId>
  </PropertyGroup>

</Project>
