name: Core Library CD
on:
  push:
    tags:
      - 'v*.*.*'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_FEED: https://nuget.pkg.github.com/luca16s/index.json
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Realizando checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Preparando .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restaurando pacotes
      run: dotnet restore
    - name: Construindo projetos
      run: dotnet build -c Release --no-restore
    - name: Buscando versão e publicando pacote
      run: |
        arrTag = (${GITHUB_REF//\//})
        VERSION = "${arrTag[2]}"
        VERSION = "${VERSION//v}"
        dotnet pack --configuration Release p:PackageVersion=$VERSION --output out
        dotnet nuget push "out\*.nupkg" --api-key $GITHUB_TOKEN --source "$GITHUB_FEED" --skip-duplicate

